CUDA_VISIBLE_DEVICES=1 python examples/rec_video.py \
    --ae WFVAEModel_D8_4x8x8 \
    --ae_path "/home/image_data/lb/Open-Sora-Plan/WFVAE_DISTILL_FORMAL" \
    --video_path /home/image_data/000001.mp4 \
    --rec_path rec_tile.mp4 \
    --device cuda \
    --sample_rate 1 \
    --num_frames 93 \
    --height 256 \
    --width 256 \
    --fps 30 \
    --enable_tiling