export TASK_QUEUE_ENABLE=0
torchrun --nnodes=1 --nproc_per_node 8 --master_port 29513 \
    -m opensora.sample.sample \
    --model_type "transition" \
    --model_path "/home/save_dir/pretrained/i2v_ckpt14777_ema" \
    --version v1_2 \
    --num_frames 93 \
    --height 480 \
    --width 640 \
    --max_hw_square 1048576 \
    --crop_for_hw \
    --cache_dir "../cache_dir" \
    --text_encoder_name_1 "/home/image_data/mt5-xxl" \
    --text_prompt "/home/image_data/chengxinhua/Open-Sora-Plan/inference/prompt.txt" \
    --ae WFVAEModel_D8_4x8x8 \
    --ae_path "/home/image_data/lb/Open-Sora-Plan/WFVAE_DISTILL_FORMAL" \
    --save_img_path "./transition_inference" \
    --fps 24 \
    --guidance_scale 5. \
    --num_sampling_steps 50 \
    --max_sequence_length 512 \
    --sample_method EulerAncestralDiscrete \
    --motion_score 0.95 \
    --num_samples_per_prompt 1 \
    --prediction_type "v_prediction" \
    --rescale_betas_zero_snr \
    --conditional_images_path "/home/image_data/chengxinhua/Open-Sora-Plan/inference/cond_paths.txt" \
    --enable_tiling 
